# Generated by Django 4.2.13 on 2024-05-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_productes', models.PositiveIntegerField()),
                ('preu_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estat', models.CharField(default='oberta', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto')),
            ],
        ),
    ]
