# Generated by Django 4.2.13 on 2024-05-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.CharField(default='obert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.PositiveIntegerField(default=1)),
                ('Producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.producte')),
                ('carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto')),
            ],
        ),
    ]
