# Generated by Django 4.2.13 on 2024-05-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('data_caducitat', models.DateField()),
                ('cvc', models.CharField(max_length=3)),
                ('estat', models.CharField(default='pendent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comandes.comanda')),
            ],
        ),
    ]
